[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "quickstart-pytorch"
version = "0.1.0"
description = "Federated Deepfake Detection"

dependencies = [
    "flwr[simulation]==1.13.1",
    "torch==2.3.1",
    "torchvision==0.18.1",
    "torchaudio==2.3.1",
    "numpy==1.26.4",
    "scikit-learn",
    "tqdm"
]

[tool.flwr.app]
publisher = "rishi"

[tool.flwr.app.config]
num-server-rounds = 3

[tool.flwr.app.components]
serverapp = "pytorchexample.server_app:app"
clientapp = "pytorchexample.client_app:app"

[tool.flwr.federations]
default = "local-simulation"

[tool.flwr.federations.local-simulation]
options.num-supernodes = 2

[tool.hatch.build.targets.wheel]
packages = ["pytorchexample"]