[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "quickstart-pytorch"
version = "0.1.0"
description = "Federated Deepfake Detection"

dependencies = [
    "flwr[simulation]==1.13.1",
    "torch==2.3.1",
    "torchvision==0.18.1",
    "torchaudio==2.3.1",
    "numpy==1.26.4",
    "scikit-learn==1.9.0",
    "tqdm==4.68.1",
    "Pillow==12.2.0",
    "PyYAML==6.0.3",
    "requests==2.34.2"
]

[tool.flwr.app]
publisher = "rishi"

[tool.flwr.app.config]
num-server-rounds = 5
local-epochs = 5
model-name = "resnet18"
dataset-name = "140k"

[tool.flwr.app.components]
serverapp = "pytorchexample.server_app:app"
clientapp = "pytorchexample.client_app:app"

[tool.flwr.federations]
default = "local-simulation"

[tool.flwr.federations.local-simulation]
options.num-supernodes = 5

[tool.flwr.federations.local-simulation.options.backend.client-resources]
num-cpus = 2
num-gpus = 1.0

[tool.hatch.build.targets.wheel]
packages = ["pytorchexample"]